/**
 * Database schema — SQL CREATE TABLE statements.
 *
 * Each table uses a TEXT primary key `id` (UUID) generated by `generateId()`.
 * Add new tables or columns here and bump SCHEMA_VERSION when the schema
 * changes. Forward-only migration steps belong in migrations.ts.
 */

export const SCHEMA_VERSION = 11;

export const CREATE_TABLES_SQL = `
  CREATE TABLE IF NOT EXISTS exercises (
    id           TEXT PRIMARY KEY NOT NULL,
    name         TEXT NOT NULL,
    muscle_group TEXT NOT NULL,
    how_to       TEXT,
    equipment    TEXT,
    strength_estimation_mode TEXT NOT NULL DEFAULT 'limited',
    is_deleted   INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS routines (
    id         TEXT PRIMARY KEY NOT NULL,
    name       TEXT NOT NULL,
    notes      TEXT,
    is_deleted INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS routine_exercises (
    id          TEXT PRIMARY KEY NOT NULL,
    routine_id  TEXT NOT NULL,
    exercise_id TEXT NOT NULL,
    position    INTEGER NOT NULL,
    target_sets INTEGER NOT NULL,
    target_reps INTEGER NOT NULL,
    rest_seconds INTEGER,
    progression_policy TEXT NOT NULL DEFAULT 'double_progression',
    target_rir REAL
  );

  CREATE INDEX IF NOT EXISTS idx_routine_exercises_routine
    ON routine_exercises (routine_id);
  CREATE INDEX IF NOT EXISTS idx_routine_exercises_exercise
    ON routine_exercises (exercise_id);

  CREATE TABLE IF NOT EXISTS routine_exercise_sets (
    id                  TEXT PRIMARY KEY NOT NULL,
    routine_exercise_id TEXT NOT NULL,
    position            INTEGER NOT NULL,
    target_reps         INTEGER NOT NULL,
    planned_weight      REAL,
    target_reps_min     INTEGER,
    target_reps_max     INTEGER,
    set_role            TEXT NOT NULL DEFAULT 'work'
  );

  CREATE INDEX IF NOT EXISTS idx_routine_exercise_sets_routine_exercise
    ON routine_exercise_sets (routine_exercise_id);

  CREATE TABLE IF NOT EXISTS schedules (
    id               TEXT PRIMARY KEY NOT NULL,
    name             TEXT NOT NULL,
    is_active        INTEGER NOT NULL DEFAULT 0,
    current_position INTEGER NOT NULL DEFAULT -1,
    is_deleted       INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS schedule_entries (
    id          TEXT PRIMARY KEY NOT NULL,
    schedule_id TEXT NOT NULL,
    routine_id  TEXT NOT NULL,
    position    INTEGER NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_schedule_entries_schedule
    ON schedule_entries (schedule_id);
  CREATE INDEX IF NOT EXISTS idx_schedule_entries_routine
    ON schedule_entries (routine_id);

  CREATE TABLE IF NOT EXISTS workout_sessions (
    id            TEXT PRIMARY KEY NOT NULL,
    routine_id    TEXT,
    schedule_id   TEXT,
    snapshot_name TEXT,
    start_time    INTEGER NOT NULL,
    end_time      INTEGER,
    effort_level  INTEGER,
    fatigue_level INTEGER,
    template_applied_at INTEGER
  );

  CREATE INDEX IF NOT EXISTS idx_workout_sessions_routine
    ON workout_sessions (routine_id);
  CREATE INDEX IF NOT EXISTS idx_workout_sessions_schedule
    ON workout_sessions (schedule_id);

  CREATE TABLE IF NOT EXISTS workout_session_exercises (
    id          TEXT PRIMARY KEY NOT NULL,
    session_id  TEXT NOT NULL,
    exercise_id TEXT NOT NULL,
    position    INTEGER NOT NULL,
    rest_seconds INTEGER,
    progression_policy TEXT NOT NULL DEFAULT 'double_progression',
    target_rir REAL
  );

  CREATE INDEX IF NOT EXISTS idx_workout_session_exercises_session
    ON workout_session_exercises (session_id);

  CREATE TABLE IF NOT EXISTS workout_sets (
    id           TEXT PRIMARY KEY NOT NULL,
    session_id   TEXT NOT NULL,
    exercise_id  TEXT NOT NULL,
    position     INTEGER,
    weight       REAL NOT NULL,
    reps         INTEGER NOT NULL,
    is_completed INTEGER NOT NULL DEFAULT 0,
    target_sets  INTEGER,
    target_reps  INTEGER,
    target_reps_min INTEGER,
    target_reps_max INTEGER,
    actual_rir REAL,
    set_role TEXT NOT NULL DEFAULT 'work'
  );

  CREATE INDEX IF NOT EXISTS idx_workout_sets_session
    ON workout_sets (session_id);
  CREATE INDEX IF NOT EXISTS idx_workout_sets_exercise
    ON workout_sets (exercise_id);

  CREATE TABLE IF NOT EXISTS body_weight_entries (
    id               TEXT PRIMARY KEY NOT NULL,
    weight           REAL NOT NULL,
    unit             TEXT NOT NULL DEFAULT 'kg',
    logged_at        INTEGER NOT NULL,
    notes            TEXT,
    source           TEXT NOT NULL DEFAULT 'manual',
    source_record_id TEXT,
    source_app       TEXT,
    imported_at      INTEGER
  );

  CREATE INDEX IF NOT EXISTS idx_body_weight_entries_logged_at
    ON body_weight_entries (logged_at);
  CREATE UNIQUE INDEX IF NOT EXISTS idx_body_weight_entries_source_record
    ON body_weight_entries (source, source_record_id);

  CREATE TABLE IF NOT EXISTS daily_step_entries (
    id               TEXT PRIMARY KEY NOT NULL,
    day_key          TEXT NOT NULL,
    step_count       INTEGER NOT NULL,
    source           TEXT NOT NULL DEFAULT 'apple_health',
    source_record_id TEXT,
    imported_at      INTEGER
  );

  CREATE UNIQUE INDEX IF NOT EXISTS idx_daily_step_entries_day_source
    ON daily_step_entries (day_key, source);

  CREATE TABLE IF NOT EXISTS health_sync_state (
    provider                TEXT PRIMARY KEY NOT NULL,
    last_body_weight_sync_at INTEGER,
    last_steps_sync_at      INTEGER,
    last_status             TEXT NOT NULL DEFAULT 'idle',
    last_error              TEXT,
    updated_at              INTEGER NOT NULL
  );

  CREATE TABLE IF NOT EXISTS user_profile (
    id                    TEXT PRIMARY KEY NOT NULL,
    display_name          TEXT,
    preferred_weight_unit TEXT NOT NULL DEFAULT 'kg',
    created_at            INTEGER NOT NULL,
    updated_at            INTEGER NOT NULL
  );

  CREATE TABLE IF NOT EXISTS training_goals (
    id TEXT PRIMARY KEY NOT NULL,
    goal_type TEXT NOT NULL,
    exercise_id TEXT,
    muscle_group TEXT,
    target_load REAL,
    target_reps INTEGER,
    target_sessions_per_week INTEGER,
    target_sets_per_week INTEGER,
    target_weeks INTEGER,
    start_time INTEGER,
    end_time INTEGER,
    status TEXT NOT NULL DEFAULT 'active',
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_training_goals_status
    ON training_goals (status);
`;
